### ISSUE TITLE
funny stuff

### ISSUE THREAD

**Issue by ghost** [ajayrandhawa/Basic-Bootstrap-Php-Ecommerce#1]
you should run a grep -r "$sql" on you r shit and u can see what i see.

**Comment by ajayrandhawa** [comment]
This is basic project  for school, there is not for production

**Comment by ajayrandhawa** [comment]
null

**Comment by ghost** [comment]
or is it the keylogger and such and the calls just curious im doine with it
got what i needed becareful and you should put what is and is not for
production and what does and does not work, But again not bad my man ivery
useful.
Matthew McGehee
ALLGLASS
314-479-1311
